name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
#    - uses: actions/checkout@v4
    - name: Build Docker Frontend Image
#      workking-directory: "CarTeck/src/API/CTK.API"
#      run: docker build . --file Dockerfile --tag CTK-API:latest
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: CTK-Client
          tags: v1,latest
          registry: ghcr.io
          dockerfile: "CarTeck/src/Client/Client/Dockerfile" # Ensure the correct case and path
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN secret for Docker authentication

    - name: Build Docker Backend Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: CTK-API
          tags: v1,latest
          registry: ghcr.io
          dockerfile: "CarTeck/src/API/CTK.API"  # Path to Dockerfile
          username: ${{ github.actor }}
          password: ${{ github.token }}
